#!/bin/sh
set -eu

project_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
source_file="$project_dir/master/ETHER_POISON_IMPORTED.pine"
output_file="$project_dir/ETHER_POISON_STANDALONE.pine"
temporary_file=$(mktemp)
trap 'rm -f "$temporary_file"' EXIT HUP INT TERM

awk '
BEGIN { inserted = 0 }
/^import ClassicPotatoChamberXII\/EP_Math\/[0-9]+ as epMath$/ { next }
/^import ClassicPotatoChamberXII\/EP_Types\/[0-9]+ as epTypes$/ { next }
/^import ClassicPotatoChamberXII\/EP_Nocturne\/[0-9]+ as nocturne$/ { next }
/^import ClassicPotatoChamberXII\/EP_Engines\/[0-9]+ as epEngines$/ {
    print ""
    print "enum Direction"
    print "    LONG = \"LONG\""
    print "    SHORT = \"SHORT\""
    print "    WAIT = \"WAIT\""
    print ""
    print "enum EntropyState"
    print "    ORDERED = \"ORDERED\""
    print "    MIXED = \"MIXED\""
    print "    DIFFUSE = \"DIFFUSE\""
    print "    CHAOTIC = \"CHAOTIC\""
    print ""
    print "enum CloudLane"
    print "    FAST = \"FAST\""
    print "    BALANCED = \"BALANCED\""
    print "    SLOW = \"SLOW\""
    print ""
    print "type CloudState"
    print "    float spanA = na"
    print "    float spanB = na"
    print "    float center = na"
    print "    float widthAtr = 0.0"
    print "    float direction = 0.0"
    print "    float entropyFast = 1.0"
    print "    float entropyMedium = 1.0"
    print "    float entropySlow = 1.0"
    print "    float entropyComposite = 1.0"
    print "    float tempAtten = 0.0"
    print "    float densityFast = 0.0"
    print "    float densityMedium = 0.0"
    print "    float densitySlow = 0.0"
    print "    float agreement = 0.0"
    print "    float confidence = 0.0"
    print "    EntropyState entropyState = EntropyState.CHAOTIC"
    print "    CloudLane dominantLane = CloudLane.BALANCED"
    print "    bool valid = false"
    print ""
    print "fEntropyName(EntropyState state) =>"
    print "    state == EntropyState.ORDERED ? \"ORDERED\" : state == EntropyState.MIXED ? \"MIXED\" : state == EntropyState.DIFFUSE ? \"DIFFUSE\" : \"CHAOTIC\""
    print ""
    print "fLaneName(CloudLane lane) =>"
    print "    lane == CloudLane.FAST ? \"FAST\" : lane == CloudLane.SLOW ? \"SLOW\" : \"BALANCED\""
    print ""
    print "fClamp(float value, float low, float high) =>"
    print "    math.max(low, math.min(high, value))"
    print ""
    print "fWeightedMean(float numerator, float denominator) =>"
    print "    denominator > 0.0 ? numerator / denominator : 0.0"
    print ""
    print "fNorm(float value, float scale) =>"
    print "    fClamp(value / math.max(math.abs(scale), 1e-6), -1.0, 1.0)"
    print ""
    print "fBlend3(float a, float wa, float b, float wb, float c, float wc) =>"
    print "    float weightA = math.max(wa, 0.0)"
    print "    float weightB = math.max(wb, 0.0)"
    print "    float weightC = math.max(wc, 0.0)"
    print "    fWeightedMean(a * weightA + b * weightB + c * weightC, weightA + weightB + weightC)"
    print ""
    print "fBinaryEntropy(float probability) =>"
    print "    float p = fClamp(probability, 1e-6, 1.0 - 1e-6)"
    print "    -(p * math.log(p) + (1.0 - p) * math.log(1.0 - p)) / math.log(2.0)"
    print ""
    print "fTempAtten(float entropy, float temperature, float floorValue) =>"
    print "    fClamp(math.exp(-math.max(temperature, 0.0) * fClamp(entropy, 0.0, 1.0)), fClamp(floorValue, 0.0, 1.0), 1.0)"
    print ""
    print "fAgreement(float a, float b, float c) =>"
    print "    fClamp(1.0 - (math.abs(a - b) + math.abs(b - c) + math.abs(a - c)) / 3.0, 0.0, 1.0)"
    print ""
    print "fCloudConfidence(float direction, float agreementValue, float inverseEntropy) =>"
    print "    fClamp(math.abs(direction) * 0.45 + agreementValue * 0.30 + inverseEntropy * 0.25, 0.0, 1.0)"
    print ""
    print "fMidpoint(float highValue, float lowValue) =>"
    print "    (highValue + lowValue) * 0.5"
    print ""
    print "fKineticMagnitude(float source, float sourcePast, float atrValue, float scale) =>"
    print "    float raw = math.abs(source - sourcePast) / math.max(atrValue, 1e-6)"
    print "    float bounded = math.min(raw / math.max(scale, 1e-6), 1.0)"
    print "    math.min(math.tan(bounded * math.pi / 4.0), 1.0)"
    print ""
    print "fZScore(float source, simple int length) =>"
    print "    float basis = ta.sma(source, length)"
    print "    float deviation = ta.stdev(source, length)"
    print "    deviation > 0.0 ? (source - basis) / deviation : 0.0"
    print ""
    print "fRescueQuantity(float currentQuantity, float currentAverage, float rescuePrice, float targetAverage, bool isLong, float maximumMultiple) =>"
    print "    float denominator = isLong ? targetAverage - rescuePrice : rescuePrice - targetAverage"
    print "    float numerator = isLong ? currentQuantity * (currentAverage - targetAverage) : currentQuantity * (targetAverage - currentAverage)"
    print "    float rawQuantity = denominator > 0.0 and numerator > 0.0 ? numerator / denominator : 0.0"
    print "    math.min(rawQuantity, currentQuantity * math.max(maximumMultiple, 0.0))"
    print ""
    print "fMultiplexerCloud(float source, float atrValue, simple int fastLength, simple int mediumLength, simple int slowLength, float temperature, float attenuationFloor, float contourAtr) =>"
    print "    int fastN = math.max(fastLength, 2)"
    print "    int mediumN = math.max(mediumLength, fastN + 1)"
    print "    int slowN = math.max(slowLength, mediumN + 1)"
    print "    float atrSafe = math.max(math.abs(atrValue), 1e-6)"
    print "    float returnNorm = fNorm(source - source[1], atrSafe)"
    print "    float localEntropy = fBinaryEntropy(fClamp(0.5 + returnNorm * 0.5, 1e-6, 1.0 - 1e-6))"
    print "    float entropyFast = ta.ema(localEntropy, fastN)"
    print "    float entropyMedium = ta.ema(localEntropy, mediumN)"
    print "    float entropySlow = ta.ema(localEntropy, slowN)"
    print "    float entropyComposite = fBlend3(entropyFast, 1.0, entropyMedium, 1.0, entropySlow, 1.0)"
    print "    float attenuation = fTempAtten(entropyComposite, temperature, attenuationFloor)"
    print "    float directionFast = fNorm(ta.ema(source - source[1], fastN), atrSafe)"
    print "    float directionMedium = fNorm(ta.ema(source - source[1], mediumN), atrSafe)"
    print "    float directionSlow = fNorm(ta.ema(source - source[1], slowN), atrSafe)"
    print "    float densityFast = math.max(1.0 - entropyFast, 0.0) * attenuation"
    print "    float densityMedium = math.max(1.0 - entropyMedium, 0.0) * attenuation"
    print "    float densitySlow = math.max(1.0 - entropySlow, 0.0) * attenuation"
    print "    float densityTotal = densityFast + densityMedium + densitySlow"
    print "    float centerFast = ta.ema(source, fastN)"
    print "    float centerMedium = ta.ema(source, mediumN)"
    print "    float centerSlow = ta.ema(source, slowN)"
    print "    float center = densityTotal > 0.0 ? fBlend3(centerFast, densityFast, centerMedium, densityMedium, centerSlow, densitySlow) : centerMedium"
    print "    float direction = densityTotal > 0.0 ? fBlend3(directionFast, densityFast, directionMedium, densityMedium, directionSlow, densitySlow) : 0.0"
    print "    float laneAgreement = fAgreement(directionFast, directionMedium, directionSlow)"
    print "    float cloudConfidence = fCloudConfidence(direction, laneAgreement, 1.0 - entropyComposite)"
    print "    float widthAtr = math.max(contourAtr, 0.0) * (0.35 + entropyComposite * 0.65) * (0.50 + math.abs(direction) * 0.50) * attenuation"
    print "    float directionalShift = direction * atrSafe * widthAtr * 0.35"
    print "    float halfWidth = atrSafe * widthAtr"
    print "    float spanA = center + directionalShift + halfWidth"
    print "    float spanB = center + directionalShift - halfWidth"
    print "    EntropyState entropyState = entropyComposite <= 0.25 ? EntropyState.ORDERED : entropyComposite <= 0.50 ? EntropyState.MIXED : entropyComposite <= 0.75 ? EntropyState.DIFFUSE : EntropyState.CHAOTIC"
    print "    CloudLane dominantLane = densityFast >= densityMedium and densityFast >= densitySlow ? CloudLane.FAST : densitySlow >= densityFast and densitySlow >= densityMedium ? CloudLane.SLOW : CloudLane.BALANCED"
    print "    CloudState.new(spanA, spanB, center, widthAtr, direction, entropyFast, entropyMedium, entropySlow, entropyComposite, attenuation, densityFast, densityMedium, densitySlow, laneAgreement, cloudConfidence, entropyState, dominantLane, not na(spanA) and not na(spanB))"
    print ""
    print "fNocturneClampAlpha(float value) =>"
    print "    int(math.round(math.max(0.0, math.min(100.0, value))))"
    print ""
    print "fNocturneDensityAlpha(float confidence, float entropy, float tempAtten, int lightAlpha, int darkAlpha) =>"
    print "    float visibility = math.max(0.0, math.min(1.0, confidence * tempAtten * (1.0 - entropy * 0.45)))"
    print "    fNocturneClampAlpha(darkAlpha - visibility * math.max(darkAlpha - lightAlpha, 0))"
    print ""
    print "fNocturneDirectionalColor(color bull, color bear, color neutral, float direction, float deadband, int alpha) =>"
    print "    color base = direction > deadband ? bull : direction < -deadband ? bear : neutral"
    print "    color.new(base, fNocturneClampAlpha(alpha))"
    print ""
    print "fNocturneSpectralColor(color base, float density, int faintAlpha, int strongAlpha) =>"
    print "    float boundedDensity = math.max(0.0, math.min(1.0, density))"
    print "    color.new(base, fNocturneClampAlpha(faintAlpha - boundedDensity * math.max(faintAlpha - strongAlpha, 0)))"
    next
}
{
    gsub(/epEngines\.kineticMagnitude/, "fKineticMagnitude")
    gsub(/epEngines\.midpoint/, "fMidpoint")
    gsub(/epEngines\.zScore/, "fZScore")
    gsub(/epEngines\.rescueQuantity/, "fRescueQuantity")
    gsub(/epEngines\.multiplexerCloud/, "fMultiplexerCloud")
    gsub(/epMath\.weightedMean/, "fWeightedMean")
    gsub(/epTypes\.Direction/, "Direction")
    gsub(/epTypes\.CloudState/, "CloudState")
    gsub(/epTypes\.entropyName/, "fEntropyName")
    gsub(/epTypes\.laneName/, "fLaneName")
    gsub(/nocturne\.densityAlpha/, "fNocturneDensityAlpha")
    gsub(/nocturne\.directionalColor/, "fNocturneDirectionalColor")
    gsub(/nocturne\.spectralColor/, "fNocturneSpectralColor")
    print
}
' "$source_file" > "$temporary_file"

mv "$temporary_file" "$output_file"
trap - EXIT HUP INT TERM
echo "$output_file"
