#!/usr/bin/env python3
"""Inline actual library sources, respecting identifiers, comments and strings.
This is a deterministic source bundler, not a Pine compiler.
"""
from pathlib import Path
import argparse, re, hashlib, json
ROOT = Path(__file__).resolve().parents[1]
IMPORT = re.compile(r'^import (\w+)/(\w+)/(\d+) as (\w+)\s*$', re.M)
CONFIG=json.loads((ROOT/'imports.json').read_text())
CATALOG={(i['name'],str(i['version'])):Path(i['file']).name for i in CONFIG['libraries']}
TOKENS = re.compile(r'//[^\n]*|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*')
def rewrite(source, mapping):
    def sub(m):
        token=m.group()
        if token.startswith(('//','"',"'")): return token
        # A namespace/type member can continue after the mapped prefix.
        parts=token.split('.')
        for n in range(len(parts),0,-1):
            key='.'.join(parts[:n])
            if key in mapping: return '.'.join([mapping[key]]+parts[n:])
        return token
    return TOKENS.sub(sub,source)
def build():
    emitted={}; bindings={}; hashes={}; visiting=set()
    def load(name,version):
        key=(name,version)
        if key in emitted: return emitted[key][0]
        if key not in CATALOG: raise ValueError(f'Unmapped library {name}/{version}')
        if key in visiting: raise ValueError(f'Cyclic import {name}/{version}')
        visiting.add(key)
        path=ROOT/'libraries'/CATALOG[key]; source=path.read_text()
        hashes[str(path.relative_to(ROOT))]=hashlib.sha256(path.read_bytes()).hexdigest()
        local={}
        for owner,dep,ver,alias in IMPORT.findall(source):
            if owner!=CONFIG['owner']: raise ValueError('Unexpected library owner')
            for symbol,target in load(dep,ver).items(): local[f'{alias}.{symbol}']=target
        # Exported vocabulary + any private top-level helper functions.
        symbols=re.findall(r'^(?:export )?(?:enum|type) (\w+)|^(?:export )?(\w+)\s*\(',source,re.M)
        names={a or b for a,b in symbols}-{ 'library' }
        own={n:f'{name}_{n}' for n in names}
        local.update(own)
        body=IMPORT.sub('',source)
        body=re.sub(r'^//@version=.*\n|^library\([^\n]*\)\s*\n','',body,flags=re.M)
        body=re.sub(r'^export ','',body,flags=re.M)
        body=rewrite(body,local)
        emitted[key]=(own,f'// BEGIN {name}/{version}\n{body.strip()}\n// END {name}/{version}\n')
        visiting.remove(key)
        return own
    master=ROOT/'master/ETHER_POISON_LIBRARY_MASTER.pine'; source=master.read_text()
    for owner,name,version,alias in IMPORT.findall(source):
        if owner!=CONFIG['owner']: raise ValueError('Unexpected library owner')
        for symbol,target in load(name,version).items(): bindings[f'{alias}.{symbol}']=target
    # Resolve imports before splitting the declaration/header from the body.
    first=IMPORT.search(source)
    if not first: raise ValueError('Master has no imports')
    header=source[:first.start()]
    body=rewrite(IMPORT.sub('',source[first.start():]),bindings)
    output=header+'// GENERATED by tools/build.py; edit master/ and libraries/.\n\n'
    output+='\n'.join(item[1] for item in emitted.values())+'\n'+body.lstrip()
    code_only=re.sub(r'//[^\n]*|"(?:\\.|[^"\\])*"', '', output)
    if re.search(r'^import |\b(?:epMath|epTypes|epEngines|nocturne|epCandles|epKinetic|epSpatial|epRescue|epGrid|epLedger|epMarket|epLimit|epCloud)\.',code_only,re.M):
        raise ValueError('Unresolved import/namespace')
    hashes[str(master.relative_to(ROOT))]=hashlib.sha256(master.read_bytes()).hexdigest()
    return output,hashes
if __name__=='__main__':
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    output,hashes=build(); target=ROOT/'ETHER_POISON_LIBRARY_PREVIEW.pine'
    if args.check:
        if not target.exists() or target.read_text()!=output: raise SystemExit('FAIL: generated standalone is stale')
        print('PASS: standalone matches master and actual libraries')
    else:
        target.write_text(output)
        (ROOT/'BUILD_MANIFEST.json').write_text(json.dumps(hashes,indent=2)+'\n')
        print(target)
