<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><TargetFramework>net6.0</TargetFramework><OutputType>Exe</OutputType><EnableDefaultCompileItems>false</EnableDefaultCompileItems><LangVersion>10</LangVersion></PropertyGroup>
 <ItemGroup><Compile Include="KernelTests.cs"/><ProjectReference Include="../mojaTyMoja.csproj"/></ItemGroup>
</Project>
